### ISSUE TITLE
Navigating directly to /recipe or /about throws a 404 error.

### ISSUE THREAD

**Issue by HarinderG** [NavreenK/navreenk.github.io#1]
https://navreenk.github.io/recipe
https://navreenk.github.io/aboutme

When I navigate to the recipe page from the home page, and then click refresh I run into a 404 error.
The same error happens when you navigate straight to the page.

![image](https://user-images.githubusercontent.com/15056631/235283718-339512f4-306b-4677-befe-d1e42eeb2d05.png)

**Comment by NavreenK** [comment]
Changed the client-side routing to use HashRouter since it seems [gh pages doesn't support SPA](https://github.com/orgs/community/discussions/36908). 

Try https://navreenk.github.io/#/recipe and https://navreenk.github.io/#/aboutme

**Comment by HarinderG** [comment]
Nice work 👏
