### ISSUE TITLE
Would like the ability to share recipes

### ISSUE THREAD

**Issue by HarinderG** [NavreenK/navreenk.github.io#2]
Navigating to a recipe does not produce a unique URL.

You could instead pass the recipe as a URL parameter when you set the link

### Something along the lines of this maybe:

When setting the link in the map functions
```js
to={`/subrecipe?id=${e.id}`}
```

When rendering a single recipe
```js
const location = useLocation()
const searchParams = new URLSearchParams(location.search)
let subrecipe = recipes.find(item => item.id === searchParams.get('id')); 
```

**Comment by HarinderG** [comment]
If you go with this idea, you will also need to render a 404 error page in the event a recipe is not found.

**Comment by NavreenK** [comment]
This enhancement has been added & we can be re-routed to a 404 page, if recipe doesn't exist. Try https://navreenk.github.io/#/subrecipe?id=2 and https://navreenk.github.io/#/subrecipe?id=800 to test both new features.
